// OpenCode Android app — root settings.
// Phase 4: a single :app module (Kotlin + Compose). The embedded runtime
// payload is generated by phase4/scripts/10-build-payload.sh into
// phase4/out/engine/ (gitignored) before the Gradle build.
pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "OpenCodeApp"
include(":app")
