// :app — the native Android shell that owns the embedded OpenCode runtime.
//
// Packaging (Core Rule: no user downloads — everything ships in the APK):
//   * Executables (bun, git, rg per ABI) are packaged as JNI libs
//     (lib<name>.so under jniLibs/<abi>/). Android extracts these into the
//     read-only, exec-allowed nativeLibraryDir — the only place an app can
//     exec from on API 29+ (W^X). extractNativeLibs=true so they are real
//     files (compressed download size), see AndroidManifest.
//   * The OpenCode server bundle, node_modules, launcher and the runtime
//     manifest ship as a compressed tar.gz under assets/ and are extracted
//     (with sha256 validation) into filesDir on first run.
//
// The payload under phase4/out/engine/ is built by
// phase4/scripts/10-build-payload.sh on a networked runner; it is gitignored.
// The preBuild task fails fast with an actionable message if it is missing.
import org.gradle.api.GradleException
import java.io.File
import java.security.MessageDigest
import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "ai.opencode.android"
    compileSdk = 34

    defaultConfig {
        // PHASE 10 — the Play application ID is PERMANENT once the app is published
        // (Play rejects a package-name change; it can only be a new listing with a
        // new key, losing installs and reviews). It is therefore deliberately
        // independent of the display name: the app is published as "OpenCode"
        // under the developer's own `io.github.mcyber12` namespace, NOT under
        // ai.opencode.android. The old value used upstream's real domain
        // (opencode.ai -> ai.opencode.*), which reads as an official/first-party
        // package and is an impersonation risk in Play review — see docs/BRANDING.md
        // (trademark status, upstream contact, rename fallback) and docs/RELEASE.md.
        //
        // The Kotlin `namespace` (R/BuildConfig package, 93 source files) stays
        // ai.opencode.android and is NOT user-visible; changing it would touch
        // every source file for zero packaging benefit.
        applicationId = "io.github.mcyber12.opencode"
        minSdk = 29          // W^X: exec only from nativeLibraryDir; ABI gating enforces arm64/x64
        targetSdk = 34
        versionCode = 8      // Phase 10: signing + store prep. Payload/version pins unchanged
                             // from Phase 9 (payloadVersion 7).
        // versionName = "<pinned OpenCode version>-phase10". Phase 5's P5-01 gate accepts
        // *phase5*..*phase10* (phase5/scripts/20-integration-gates.sh); check-lock.py
        // asserts the prefix equals versions.lock's opencode version.
        versionName = "1.18.23-phase10"   // tracks the pinned OpenCode version (versions.lock)
        ndk {
            abiFilters += listOf("arm64-v8a", "x86_64")   // arm64 ships; x86_64 for CI/emulator
        }
        // On-device integration tests run inside the app's own process: they use
        // the SAME client classes (OpenCodeApi/OpenCodeEventStream/SecretStore)
        // as the UI, against the SAME server the supervisor started.
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    // ------------------------------------------------------------------ signing
    // PHASE 10. The release keystore is generated by the human owner on a machine
    // they control and NEVER lives in this repository, in CI, or in any chat:
    // see docs/RELEASE.md for the full procedure. This build reads it from
    // OUTSIDE the repo only, in this order (first hit wins):
    //
    //   1. ~/.config/opencode-app/keystore.properties   (recommended: outside the tree)
    //   2. <repo>/keystore.properties                   (gitignored, for convenience)
    //   3. environment variables                        (for a machine that exports them
    //      from a secret manager; Phase 10's CI deliberately does NOT sign anything)
    //
    // `keystore.properties` (never `keystore.properties.example`, never a literal):
    //   storeFile=/absolute/path/to/upload-keystore.jks
    //   storePassword=...
    //   keyAlias=upload
    //   keyPassword=...
    //
    // With no keystore configured the release build stays UNSIGNED — which is what
    // CI produces — and the artifact's own name says so. A *partially* configured
    // keystore is an error, not a silent fallback: shipping an unsigned APK because
    // a password was missing is exactly the failure this project cannot afford.
    val keystoreProperties: Properties = Properties().apply {
        val f = sequenceOf(
            File(System.getProperty("user.home") ?: "", ".config/opencode-app/keystore.properties"),
            rootProject.file("keystore.properties"),
        ).firstOrNull { it.isFile }
        f?.inputStream()?.use { load(it) }
    }
    fun signingValue(prop: String, vararg envNames: String): String? {
        keystoreProperties.getProperty(prop)?.trim()?.takeIf { it.isNotEmpty() }?.let { return it }
        for (e in envNames) System.getenv(e)?.trim()?.takeIf { it.isNotEmpty() }?.let { return it }
        return null
    }
    val releaseStorePath = signingValue("storeFile", "RELEASE_KEYSTORE_FILE", "P9_KEYSTORE_FILE")
    val releaseStorePassword = signingValue("storePassword", "RELEASE_KEYSTORE_PASSWORD", "P9_KEYSTORE_PASSWORD")
    val releaseKeyAlias = signingValue("keyAlias", "RELEASE_KEY_ALIAS", "P9_KEY_ALIAS")
    val releaseKeyPassword = signingValue("keyPassword", "RELEASE_KEY_PASSWORD", "P9_KEY_PASSWORD")
    val releaseStoreFile = releaseStorePath?.let { File(it) }
    if (releaseStorePath != null && (releaseStoreFile == null || !releaseStoreFile.isFile)) {
        throw GradleException(
            "Release signing is configured (storeFile=$releaseStorePath) but that file does not exist.\n" +
                "Refusing to build: a build that silently falls back to UNSIGNED would be published as-is.\n" +
                "Fix the path, or unset the signing configuration to build a deliberately unsigned artifact."
        )
    }
    if (releaseStoreFile != null && (releaseStorePassword == null || releaseKeyAlias == null)) {
        throw GradleException(
            "Release signing is half-configured: storeFile and " +
                (if (releaseStorePassword == null) "storePassword " else "") +
                (if (releaseKeyAlias == null) "keyAlias " else "") +
                "are missing. See docs/RELEASE.md. Refusing to build an ambiguous artifact."
        )
    }
    val hasReleaseKeystore = releaseStoreFile != null
    if (hasReleaseKeystore) {
        signingConfigs {
            create("release") {
                storeFile = releaseStoreFile
                storePassword = releaseStorePassword
                keyAlias = releaseKeyAlias
                // A keystore generated by `keytool -genkeypair` normally uses one
                // password for both; PKCS#12 (the only format `keytool` writes
                // since Java 9) enforces that, so falling back is not a guess.
                keyPassword = releaseKeyPassword ?: releaseStorePassword
            }
        }
    }
    // Print the *identity* of the signing material (never a secret: the file NAME
    // and the certificate's SHA-256 are public information that belongs in a build
    // log, and are what tells a reviewer which key signed an artifact).
    val signingLine = if (hasReleaseKeystore) {
        "RELEASE SIGNING: enabled store=${releaseStoreFile!!.name} alias=$releaseKeyAlias " +
            "storeSha256=" + runCatching {
                val md = MessageDigest.getInstance("SHA-256")
                releaseStoreFile!!.readBytes().let { md.digest(it) }.joinToString("") { b -> "%02x".format(b) }.take(16)
            }.getOrDefault("n/a")
    } else {
        "RELEASE SIGNING: not configured -> release artifacts are UNSIGNED (CI behavior; see docs/RELEASE.md)"
    }

    logger.lifecycle(signingLine)

    buildTypes {
        release {
            isMinifyEnabled = false
            // No R8/ProGuard stripping: the app shell is small, keeps stack traces
            // readable for runtime diagnostics, and shipping the same code shape the
            // device gates exercised removes a whole class of release-only failure.
            // Phase 10 verified this empirically rather than assuming it: the
            // `smoke` variant below runs the full Phase 6 UI gates against
            // release-shaped code, and check-apk.py asserts the published APK
            // carries debuggable=false and the release application ID.
            if (hasReleaseKeystore) signingConfig = signingConfigs.getByName("release")
        }
        debug {
            applicationIdSuffix = ".debug"   // debug coexists; run-as works on debuggable builds
        }
        // PHASE 10 — `smoke`: the RELEASE configuration, made runnable by the
        // device gates. Same applicationId as release, same payload, same
        // (unminified) code shape, same proguard/no-proguard decision — the only
        // differences are `debuggable=true` (so `am instrument` + `run-as` can see
        // into it) and the signing key (the public AOSP debug key, because CI must
        // never touch the real release keystore).
        //
        // Why this exists: every gate in Phases 4-9 ran against the *debug*
        // applicationId, so "the release build does something different" was an
        // untested hypothesis. This variant tests it without putting a secret in CI.
        // It is never a published artifact: it is not uploaded by the Phase 10
        // workflow as a release, its APK name contains TEST-ONLY, and
        // docs/RELEASE.md states plainly that it must not be uploaded to Play.
        create("smoke") {
            initWith(getByName("release"))
            isDebuggable = true
            signingConfig = signingConfigs.getByName("debug")
            matchingFallbacks += listOf("release")
        }
    }
    // The androidTest variant follows this property; the default stays "debug" so
    // every Phase 4-9 harness invocation is unaffected. Phase 10's smoke stage runs
    // with -PtestBuildType=smoke to build app-smoke + app-smoke-androidTest APKs.
    testBuildType = (project.findProperty("testBuildType")?.toString() ?: "debug")

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
    buildFeatures {
        compose = true
        buildConfig = true   // needed for BuildConfig.DEBUG (debug control receiver)
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.5.14"
    }

    sourceSets {
        getByName("main") {
            // Build-owned copies of the runner-generated payload (populated by
            // the verifyAndStagePayload task before build). These are stable
            // directories mergeAssets/mergeJniLibs always see.
            assets.srcDir(layout.buildDirectory.dir("generated/engine/assets").get().asFile)
            jniLibs.srcDir(layout.buildDirectory.dir("generated/engine/jniLibs").get().asFile)
        }
    }

    packaging {
        jniLibs {
            useLegacyPackaging = true   // = extractNativeLibs: libs uncompressed-stored then extracted
        }
    }

    testOptions {
        unitTests.all { it.testLogging { events("passed", "skipped", "failed") } }
    }
}

dependencies {
    val composeBom = platform("androidx.compose:compose-bom:2024.06.00")
    implementation(composeBom)
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.activity:activity-compose:1.9.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.3")
    implementation("androidx.lifecycle:lifecycle-service:2.8.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    // Phase 6 UI. Both are Compose artifacts aligned by the BOM above, not new
    // third-party libraries: the chat UI needs icons (send/stop/expand) and the
    // foundation layer it was already using implicitly through material3
    // (lazy lists, clickable text, borders). Nothing else is added - markdown and
    // syntax highlighting are implemented in-repo (ui/markdown) so the dependency
    // list stays as small and as pinnable as Phase 5 left it.
    implementation("androidx.compose.material:material-icons-core")
    implementation("androidx.compose.foundation:foundation")
    // Phase 7: SAF document-tree traversal for project import/export. This is the
    // standard AndroidX wrapper over DocumentsContract — importing a folder the user
    // picked (or exporting a project as a zip) without any storage permission.
    implementation("androidx.documentfile:documentfile:1.0.1")

    testImplementation("junit:junit:4.13.2")
    // Instrumentation only: the runner + junit3 extension. No production dep is
    // added for tests (Phase 5 keeps the app's dependency list unchanged).
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test:runner:1.6.1")
    androidTestImplementation("androidx.test:core:1.6.1")
    // Phase 6 (P6-00, the prerequisite the plan of record names): without a Compose
    // UI-test dependency every UI claim would be "it compiles", which this project
    // does not accept as evidence. ui-test-manifest supplies the host activity that
    // createComposeRule() needs, in debug builds only.
    androidTestImplementation(composeBom)
    androidTestImplementation("androidx.compose.ui:ui-test-junit4")
    debugImplementation("androidx.compose.ui:ui-test-manifest")
    // Phase 10: the smoke build type runs the same Compose gates against
    // release-shaped code (see buildTypes.smoke), so it needs the test-host
    // activity in its own manifest too - `debugImplementation` alone would leave
    // createComposeRule() without an activity to host the composition.
        configurations.configureEach {
        if (name == "smokeImplementation") {
            project.dependencies.add(name, "androidx.compose.ui:ui-test-manifest")
        }
    }
    // Real org.json on the JVM so manifest parsing/markers are testable locally.
    testImplementation("org.json:json:20240303")
}

// Copy the runner-generated payload into build-owned dirs that mergeAssets /
// mergeJniLibs consume, after verifying it is complete. This both fails fast
// with an actionable message if 10-build-payload.sh was never run, and makes
// the merge tasks depend on a real Copy (so the files are always staged).
fun engineRoot(): File = rootProject.file("phase4/out/engine")
fun engineAssetsOut(): File = layout.buildDirectory.dir("generated/engine/assets").get().asFile
fun engineJniOut(): File = layout.buildDirectory.dir("generated/engine/jniLibs").get().asFile

val verifyAndStagePayload = tasks.register("verifyAndStagePayload") {
    group = "opencode"
    description = "Verifies and stages phase4/out/engine into generated asset/jniLibs dirs."
    doLast {
        // CI-only escape hatch for *compile-only* runs (no packaging): Gradle's
        // "fast feedback" job has to be able to type-check ~2,600 new Kotlin lines
        // without first spending 10-15 minutes building the embedded runtime. It is
        // opt-in (-PskipPayload) and only ever passed together with compile*/test
        // tasks, never assemble*/package*; an APK could not have been produced by a
        // build that skipped this, and one that somehow was would not start (the
        // extractor fails closed on the missing asset).
        // Read the switch from the environment as well as the property, and print
        // what was seen: an earlier version relied on `-PskipPayload` alone, the
        // CI run then failed on the missing payload with no explanation, and the
        // mismatch was only visible by reading the whole log. A diagnostic makes the
        // next such confusion self-evident instead of costing a run.
        val skipProp = project.findProperty("skipPayload")?.toString()
        val skipEnv = System.getenv("SKIP_PAYLOAD")
        println("PAYLOAD STAGING: -PskipPayload=$skipProp SKIP_PAYLOAD=$skipEnv")
        if (skipProp in setOf("true", "1", "") || skipEnv in setOf("1", "true", "yes")) {
            println("PAYLOAD STAGING SKIPPED: compile/test-only run, no APK was produced.")
            return@doLast
        }
        val root = engineRoot()
        val srcAssets = File(root, "assets")
        val srcJni = File(root, "jniLibs")
        val mf = File(srcAssets, "runtime-manifest.json")
        if (!mf.isFile) {
            throw GradleException(
                "Embedded runtime payload missing: ${mf.path} not found.\n" +
                    "Run:  bash phase4/scripts/10-build-payload.sh   (needs network; see phase4/README.md)\n" +
                    "It builds Bun-for-Android, Android/Bionic Git and ripgrep, and the pinned OpenCode bundle " +
                    "into phase4/out/engine/."
            )
        }
        val libs = listOf("libbun.so", "libgit.so", "librg.so", "libseccompshim.so", "libexecshim.so", "libchildshim.so")
        val abis = listOf("arm64-v8a", "x86_64")
        var completeAbis = 0
        for (abi in abis) {
            val abiDir = File(srcJni, abi)
            val present = libs.map { File(abiDir, it) }
            val have = present.count { it.isFile }
            if (have == 0) {
                println("Runtime payload note: ABI $abi not built (skipped; pass it to 10-build-payload.sh).")
                continue
            }
            if (have != libs.size) {
                val missing = present.filterNot { it.isFile }
                throw GradleException("Runtime payload incomplete for ABI $abi: missing ${missing.map { it.name }}")
            }
            completeAbis++
        }
        if (completeAbis == 0) {
            throw GradleException("Runtime payload incomplete: no JNI exec libs found under $srcJni")
        }
        val assetsDst = engineAssetsOut()
        val jniDst = engineJniOut()
        assetsDst.deleteRecursively(); assetsDst.mkdirs()
        jniDst.deleteRecursively(); jniDst.mkdirs()
        srcAssets.copyRecursively(assetsDst, overwrite = true)
        srcJni.copyRecursively(jniDst, overwrite = true)
        println("Runtime payload OK: $completeAbis complete ABI(s); staged assets + jniLibs to $assetsDst / $jniDst")
    }
}

tasks.named("preBuild") {
    dependsOn(verifyAndStagePayload)
}
